---
# handlers file for etcd_cluster

# Restart masters one-by-one to keep quorum
- name: Restart etcd masters
  become: true
  become_user: root
  when: etcd_launch | bool
  ansible.builtin.service:
    name: etcd
    state: restarted
  run_once: true
  loop: '{{ groups[etcd_master_group_name] }}'
  delegate_to: '{{ item }}'

# Restart non-voting members
- name: Restart etcd members
  become: true
  become_user: root
  when:
    - etcd_launch | bool
    - inventory_hostname is not in (groups[etcd_master_group_name])
  ansible.builtin.service:
    name: etcd
    state: restarted
